### ISSUE TITLE
Issue in auth.service.ts 

### ISSUE THREAD

**Issue by ghost** [gugui3z24/MEAN-Stack-With-Angular-2-Tutorial#14]
registerUser(user) {
    return this.http.post(this.domain + 'authentication/register', user).map(res => res.json());
  }
// and others

i got some error in .map(res => res.json());

ERROR in src/app/services/auth.service.ts:22:74 - error TS2339: Property 'map' does not exist on type 'Observable<Object>'.

22     return this.http.post(this.domain +'/authentication/register',user ).map(res => res.json());

(https://user-images.githubusercontent.com/43374749/80504269-7bed9b80-89a5-11ea-8bd5-1e84d514b25b.png

**Comment by ghost** [comment]
https://user-images.githubusercontent.com/43374749/80504446-b6573880-89a5-11ea-8789-a9eb624e338b.png

**Comment by JmPaunlagui** [comment]
core.js:6210 ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(AppModule)[AuthService -> Http -> Http -> Http]: 
  NullInjectorError: No provider for Http!
NullInjectorError: R3InjectorError(AppModule)[AuthService -> Http -> Http -> Http]: 
  NullInjectorError: No provider for Http!
    at NullInjector.get (core.js:1085)
    at R3Injector.get (core.js:16815)
    at R3Injector.get (core.js:16815)
    at R3Injector.get (core.js:16815)
    at injectInjectorOnly (core.js:940)
    at Module.ɵɵinject (core.js:950)
    at Object.AuthService_Factory [as factory] (auth.service.ts:8)
    at R3Injector.hydrate (core.js:17053)
    at R3Injector.get (core.js:16803)
    at NgModuleRef$1.get (core.js:36454)
    at resolvePromise (zone-evergreen.js:798)
    at resolvePromise (zone-evergreen.js:750)
    at zone-evergreen.js:860
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41762)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:484)
    at invokeTask (zone-evergreen.js:1621)

**Comment by ghost** [comment]
core.js:6210 ERROR DOMException: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL
    at http://localhost:4200/polyfills.js:2873:35
    at XMLHttpRequest.proto.<computed> [as open] (http://localhost:4200/polyfills.js:1462:52)
    at Observable._subscribe (http://localhost:4200/vendor.js:60630:18)
    at Observable._trySubscribe (http://localhost:4200/vendor.js:76149:25)
    at Observable.subscribe (http://localhost:4200/vendor.js:76135:22)
    at MapOperator.call (http://localhost:4200/vendor.js:81175:23)
    at Observable.subscribe (http://localhost:4200/vendor.js:76130:31)
    at RegisterComponent.onRegisterSubmit (http://localhost:4200/main.js:865:45)
    at RegisterComponent_Template_form_submit_5_listener (http://localhost:4200/main.js:927:150)
    at executeListenerWithErrorHandling (http://localhost:4200/vendor.js:26977:16)
